digitallibrary/digitallibrary/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^tutorials/', include('tutorials.urls', namespace='books')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitallibrary/tutorials/urls.py
from django.conf.urls import urlfrom django.conf import settingsfrom . import views

app_name = 'tutorials'

urlpatterns = [        # /tutorials/
        url(r'^$', views.index, name='index'),        # /tutorials/tutorials        url(r'^view_books$', views.view_books, name='view_books'),        # /register/        url(r'^user_registration/$', views.user_registration, name='user_registration'),        # /user_login/        url(r'^user_login/$', views.user_login, name='user_login'),        # /user_logout/        url(r'^user_logout/$', views.user_logout, name='user_logout'),        # /tutorials/71/        url(r'^(?P<softwaretutorials_id>[0-9]+)/$', views.detail, name='detail'),        #/create_tutorial/        url(r'^create_tutorial/$', views.create_tutorial, name='create_tutorial'),        #/tutorials/71/create_book        url(r'^(?P<softwaretutorials_id>[0-9]+)/create_book/$', views.create_book, name='create_book'),        #/tutorials/tutorial_id/delete_book/book_id        url(r'^(?P<softwaretutorials_id>[0-9]+)/delete_book/(?P<book_id>[0-9]+)$', views.delete_book, name='delete_book'),        #/tutorials/71/delete_tutorial/        url(r'^(?P<softwaretutorials_id>[0-9]+)/delete_tutorial/$', views.delete_tutorial, name='delete_tutorial'),
    ] 

digitallibrary/tutorials/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class SoftwareTutorials(models.Model):
    language = models.CharField(max_length=250)
    language_description = models.TextField()
    creator = models.CharField(max_length=250)
    lang_logo = models.FileField()
    
    def __str__(self):
        return self.language+' '+self.creator
    

class Book(models.Model):
    softwaretutorials = models.ForeignKey(SoftwareTutorials, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=250)
    book_author = models.CharField(max_length=250)
    pdf_file = models.FileField()
    price = models.IntegerField(default=0)
    
    def __str__(self):
        return self.book_title
    

digitallibrary/tutorials/forms.py
from django import forms
from .models import SoftwareTutorials, Book
from django.contrib.auth.models import User


class SoftwareTutorialsForm(forms.ModelForm):
    
    class Meta:
        model = SoftwareTutorials
        widgets={
            'language_description' : forms.Textarea(attrs={'rows': 4, 'cols': 23}),
            }
        fields = ['language','language_description','creator','lang_logo']
        
        
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_title','book_author','pdf_file', 'price']
    


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password']

digitallibrary/tutorials/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.db.models import Q
from django.http import HttpResponse
from . models import SoftwareTutorials, Book
from . forms import SoftwareTutorialsForm, BookForm, UserForm
from django.urls import reverse
from django.http.response import HttpResponseRedirect, HttpResponseServerError
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.query import QuerySet
#from django.template import loader
# Create your views here.

def delete_tutorial(request, softwaretutorials_id):
    tuts = SoftwareTutorials.objects.get(pk=softwaretutorials_id)
    all_softwaretuts = SoftwareTutorials.objects.all()
    #template = loader.get_template('tutorials/index.html')
    try:
        tuts.delete()
        return HttpResponseRedirect('/tutorials/')
    except ObjectDoesNotExist:
        return HttpResponseServerError()
          
    context = {
        'all_softwaretuts' : all_softwaretuts
        }

    return render(request, 'tutorials/index.html', context)
    

def create_tutorial(request):
    if not request.user.is_authenticated():
        form = UserForm(request.POST or None)
        return render(request, 'tutorials/user_login.html', {'form' : form})
    else:
        form = SoftwareTutorialsForm(request.POST or None, request.FILES or None)
    
        if form.is_valid():
            #soft_tuts = form.save(commit=False)
            soft_tuts = form.save()
            
            return render(request,'tutorials/detail.html', {'soft_tuts' : soft_tuts })
            #return render(request, 'music/detail.html', {'album': album})
        
        context = {
            'form' : form
            }
        return render(request, 'tutorials/create_tutorial.html', context)


def create_book(request, softwaretutorials_id):
    form = BookForm(request.POST or None, request.FILES or None)
    soft_tuts = get_object_or_404(SoftwareTutorials, pk=softwaretutorials_id)
        
    if form.is_valid():
        #clean data
        for data in soft_tuts.book_set.all():
            if data.book_title == form.cleaned_data.get("book_title"):
                context= {
                    'soft_tuts' : soft_tuts,
                    'form' : form,
                    'error_message' : "Book already exists!!!"
                }
                return render(request,'tutorials/create_book.html', context)
        book = form.save(commit=False)
        book.softwaretutorials = soft_tuts    
        
        book.save()
        #return HttpResponse("<h1> Book created</h1>")
        print("Soft tuts:", soft_tuts)
        return render(request, 'tutorials/detail.html', { 'soft_tuts' : soft_tuts })
    
    context = {
        'soft_tuts' : soft_tuts,
        'form' : form
        }
    return render(request,'tutorials/create_book.html', context)
    #return HttpResponse('<h1>Add book here</h1>')
    
    
def delete_book(request, softwaretutorials_id, book_id):
    soft_tuts = SoftwareTutorials.objects.get(pk=softwaretutorials_id)
    book = Book.objects.get(pk=book_id)
    try:
        book.delete()
        print("book is deleted:", soft_tuts.id)
        #return HttpResponse('<h1> Hello world</h1>')
        return HttpResponseRedirect('/tutorials/'+str(soft_tuts.id)+'/')
    except Book.DoesNotExist:
        return HttpResponseServerError()
        #reverse('books/detail.html', kwargs = {'soft_tuts' : soft_tuts })
        
        #return redirect(detail, { 'soft_tuts' :soft_tuts })
        #template = loader.get_template('books/index.html')  
    context = {
        'soft_tuts' : soft_tuts
        }

    return render(request, 'tutorials/detail.html', context)

    

def view_books(request):
    
    all_softwaretuts = SoftwareTutorials.objects.all()
    
    return render(request,'tutorials/view_books.html', {'all_softwaretuts' : all_softwaretuts})




def index(request):
    if not request.user.is_authenticated():
        return render(request, 'tutorials/user_login.html')
    else:
        tutorials = SoftwareTutorials.objects.all()
        books = Book.objects.all()
        query = request.GET.get('q')
        if query:
            tutorials = tutorials.filter(
                    Q(language__icontains=query) |
                    Q(creator__icontains=query)
                ).distinct()
            books = books.filter(
                    Q(book_title__icontains=query)|
                    Q(book_author__icontains=query)
                ).distinct()
            return render(request, 'tutorials/index.html', {
                'all_softwaretuts': tutorials,
                'q_books': books,
                })
            
    all_softwaretuts = SoftwareTutorials.objects.all()
    #template = loader.get_template('tutorials/index.html')  
    context = {
        'all_softwaretuts' : all_softwaretuts
        }
    #return HttpResponse()
    #return HttpResponse(template.render(context,request))
    return render(request, 'tutorials/index.html', context)
    
    

def detail(request, softwaretutorials_id):
    try:
        soft_tuts = SoftwareTutorials.objects.get(pk=softwaretutorials_id)
    except SoftwareTutorials.DoesNotExist:
        raise Http404("Could not find Software tutorial!!!")
    
    return render(request, 'tutorials/detail.html', {'soft_tuts': soft_tuts})
    
    #return HttpResponse('<h2>Books on Software Tutorial '+str(softwaretutorials_id)+' </h2>')
    
    
def user_registration(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                print('i am here')
                all_softwaretuts = SoftwareTutorials.objects.all()
                return render(request, 'tutorials/index.html', {'all_softwaretuts' : all_softwaretuts } )
            else:
                return render(request,'tutorials/user_login.html', {'error_message': "Your account is disabled"})
        else:
            return render(request,'tutorials/user_login.html', {'error_message': "Invalid login"})
    context = {
        'form' : form
        }    
        
    return render(request,'tutorials/user_registration.html', context)
    
        

def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                tutorials = SoftwareTutorials.objects.all()
                return render(request, 'tutorials/index.html', {'all_softwaretuts' : tutorials})
            else:
                return render(request,'tutorials/user_login.html', {'error_message': "Your account is disabled"})
        else:
            return render(request,'tutorials/user_login.html', {'error_message': "Invalid login"})
         
    return render(request,'tutorials/user_login.html')
        


def user_logout(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        'form' : form
        }
    return render(request, 'tutorials/user_login.html', context)

digitallibrary/tutorials/templates/tutorials/base.html
<html>
<head lang="en">
	<meta charset="UTF-8">
	<title>{% block title %}DigitalLibrary{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}"/>
</head>
<body>
		<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			 <!-- Header -->
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
	            </button>
	            <a class="navbar-brand" href="{% url 'tutorials:index' %}">DigitalLibrary</a>
	        </div>
			
			<!-- Items -->
			<div class="collapse navbar-collapse id=topNavBar">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;Home</a></li>
					<li ><a href="{% url 'tutorials:index' %}"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp;Tutorials</a></li>
					<li ><a href="{% url 'tutorials:view_books' %}"><span class="glyphicon glyphicons-book-open" aria-hidden="true"></span>&nbsp;Books</a></li>
				</ul>
				<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'tutorials:index' %}">
	                <div class="form-group">
	                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
	                </div>
	                <button type="submit" class="btn btn-default">Search</button>
	            </form>
	            <ul class="nav navbar-nav navbar-right">
	            	<li><a href="{% url 'tutorials:create_tutorial' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Tutorial</a></li>
	            	<li><a href="{% url 'tutorials:user_logout' %}"><span class="glyphicon glyphicon-off"></span>&nbsp; Logout</a></li>
	            </ul>
			 </div>
		</div>
	</nav>
	
{% block body %}
{% endblock %}
</body>
</html>

digitallibrary/tutorials/templates/tutorials/base_user.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}DigitalLibrary{% endblock %}</title>
		{% load staticfiles %}
		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}"/>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'tutorials:index' %}">DigitalLibrary</a>
				</div>
				<!-- Items -->
				<div class="collapse navbar-collapse" id="topNavBar">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'tutorials:user_registration' %}">Register</a></li>
						<li><a href="{% url 'tutorials:user_login' %}">Login</a></li>	
					</ul>
		    	</div>
		    </div>
		</nav>
		{% block body %}
		{% endblock %}
	</body>

</html>

digitallibrary/tutorials/templates/tutorials/create_book.html
{% extends 'tutorials/base.html' %}
{% block title %}create book{% endblock %}
{% block body %}

<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'tutorials:detail' soft_tuts.id %}">
                            {% if soft_tuts.lang_logo %}
                                <img src="{{ soft_tuts.lang_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ soft_tuts.language }} <small>{{ soft_tuts.language_description }}</small></h1>
                    <h2>{{ soft_tuts.creator }}</h2>
                </div>
            </div>
        </div>
		  <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'tutorials:detail' soft_tuts.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'tutorials:create_book' soft_tuts.id %}">Add New Book</a></li>
            </ul>
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a new Book</h3>
					{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    
					<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<input type="hidden" name="soft_tuts" value="{{ soft_tuts }}">
						{% include 'tutorials/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button role="button" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>				
			</div>
		</div>
	</div>
	
</div>
{% endblock %}

digitallibrary/tutorials/templates/tutorials/create_tutorial.html
{% extends 'tutorials/base.html' %}
{% block title %}Add New Tutorial{% endblock %}


{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a new Tutorial</h3>
					<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'tutorials/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="col-sm-12 col-md-5">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>What is Digital Library?</h3>
					<p>Digital library App allows you to upload different books as pdf. Helping 
					 users to read and download online</p>
					 <h3>How to add a book?</h3>
					 <p>User have to first login, create tutorial and upload books under a tutorial section</p>
					 <h3>How to add Tutorial logo</h3>
					 <ul>
					 	<li>Have resolution of 512*512</li>
					 	<li>Use .png, .jpg formats</li>
					 	<li>Squre images looks good</li>
					 </ul>		
				</div>
			</div>
		
		</div>
	</div>

</div>


{% endblock %}

digitallibrary/tutorials/templates/tutorials/detail.html
{% extends 'tutorials/base.html' %}
{% block title %}Book{% endblock %}
{% block body %}


<div class="container-fluid">
	<div class="row">
		<!--  left: tutorial info -->
		<div class="col-sm-4 col-md-3">
			<div class="panel panel-default">
				<div class="panel-body">
					<a href="{% url 'tutorials:detail' soft_tuts.id %}">
					{% if soft_tuts.lang_logo %}
						<img src="{{ soft_tuts.lang_logo.url }}" class="img-responsive"></a>
					{% else %}
						<h3>No image</h3>
					{% endif%}
					<h1>{{ soft_tuts.language }}</h1>
					<p>{{ soft_tuts.language_description }}</p>
				</div>
			</div>
		</div>
		<!--  right: Add book info -->
		<div class="col-sm-8 col-md-9">
			  <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <!--<li role="presentation" class="active"><a href="#">View All</a></li>   -->
                <li role="presentation"><a href="{% url 'tutorials:create_book' soft_tuts.id %}">Add New Book</a></li>
            </ul>
            
            <div class="panel panel-default">
	            <div class="panel-body">
	            	<h3>All books</h3>
	            	<table class="table">
	            	<thead>
	            	<tr>
	            		<th>Book Title</th>
	            		<th>Book Author</th>
	            		<th>View/Download</th>
	            		<th>Price</th>
	            		
	            	</tr>
	            	</thead>
	            	<tbody>
	            	{% for book in all_books %}
	            	<tr>
	            		<td>{{ book.book_title }}</td>
	            		<td>{{ book.book_author }}</td>
	            		<td>
	            			<a href={{ book.pdf_file.url }}>
	            				<button type="button" class="btn btn-success btn-xs">
	            					<div class="col-sm-12 col-md-3"> <span class="glyphicon glyphicon-open"></span></div>
	            				</button>
	            			</a>
	            		</td>
	            		<td>{{ book.price }}</td>
	            		<td>
		            		<form action="{% url 'books:delete_book' soft_tuts.id book.id %}" method="post" style="display: inline;">
		            			{% csrf_token %}
			            		<input type="hidden" name="book_id" value="{{ soft_tuts.id }}"/>
			            		<button type="submit">
			            			<span class="glyphicon glyphicon-remove"></span>
			            		</button>
		            		</form>
		            	</td>
		            <tr>
	            	{% endfor %}
	            	</tbody>
	            	</table>
	            </div>
	          </div>
            </div>
		</div>
</div>

{% endblock %}

digitallibrary/tutorials/templates/tutorials/form_template.html
{% for field in form %}
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
    </div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10">{{ field }}</div> 
</div>
{% endfor %}

digitallibrary/tutorials/templates/tutorials/index.html
<!--  Load path to the static files -->
{% extends 'tutorials/base.html' %}
{% block body %}

<div class="books-container container-fluid">
	<!-- Tutorials -->
	<div class="row">
		<div class="col-sm12">
			<h3>Software Tutorials</h3>
		</div>
		{% if all_softwaretuts %}
			{% for soft_tuts in all_softwaretuts %}
				<div class="col-sm-4 col-md-3">
					<div class="thumbnail">
						<a href="{% url 'tutorials:detail' soft_tuts.id %}"><img src="{{ soft_tuts.lang_logo.url }}"></a>
						<div class="caption">
							<h2>{{ soft_tuts.language }}</h2>
	                        <p>{{ soft_tuts.language_description }}</p>
						</div>
						<!-- View Tutorial -->
						<a href="{% url 'tutorials:detail' soft_tuts.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
						<!--  Delete Tutorial -->
						<form action="{% url 'tutorials:delete_tutorial' soft_tuts.id %}" method="POST" style="display: inline">
							{% csrf_token %}
							<input type="hidden" name="soft_tuts_id" value="{{ soft_tuts.id }}"/>
							<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-trash"></span>
							</button>
						</form>
						
					</div>
					
				</div>
			{% endfor %}
		{% else %}
			<h1>Nothing to display</h1>
		{% endif %}
	</div>
{% endblock %}

digitallibrary/tutorials/templates/tutorials/user_login.html
{% extends 'tutorials/base_user.html' %}
{% block title %}Log In{% endblock %}
{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-6">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>User Login</h3>
					 {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'tutorials:user_login' %}" method="post" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	<div class="form-group">
                    		<label class="col-sm-2" for="id_username">Username:</label>
	                    		<div class="col-sm-10">
	                    			<input id="id_username" maxlength=30 name="username" type="text" >
	                    		</div>
	                    	
	                    	 <label class="col-sm-2" for="id_password">Password:</label>
	                    	 	<div class="col-sm-10">
	                    	 		<input id="id_password" name="password" type="password">
	                    	 	</div>
	                    </div>
	                    <div class="form-group">
	                    	<div class="col-sm-offset-2 col-sm-10"">
								<button type="submit"  class="btn btn-success">Submit</button>
							</div>
	                    </div>
					</form>
                </div>
                <div class="panel-footer">
                	Don't have an account? <a href="{% url 'tutorials:user_registration' %}">Click here</a> to register
                </div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

digitallibrary/tutorials/templates/tutorials/user_registration.html
{% extends 'tutorials/base_user.html' %}
{% block title %}User Registration{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-6">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>User Registration</h3>
					 {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                     {% endif %}
                     <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                     	{% csrf_token %}
                     	{% include 'tutorials/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>                     
                     </form>
				</div>
				<div class="panel-footer">
					Already have an account?<a href="{ url 'tutorials:user_login'}">Click here</a> to login.
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

digitallibrary/tutorials/templates/tutorials/view_books.html
{% extends 'tutorials/base.html' %}
{% block title %}Add New Tutorial{% endblock %}
{% block body %}
	<h3>All Books</h3>
	<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
		<table class="table">
           	<thead>
           	<tr>
           		<th>TutorialName</th>
           		<th>Book Title</th>
           		<th>Book Author</th>
           		<th>View/Download</th>
           		<th>Price</th>
           		
           	</tr>
           	</thead>
           	<tbody>
           		{% for soft_tut in all_softwaretuts %}
            		{% for book in soft_tut.book_set.all %}
		            	<tr>
		            		<td>{{ soft_tut.language }}</td>
		            		<td>{{ book.book_title }}</td>
		            		<td>{{ book.book_author }}</td>
		            		<td>
		            			<a href={{ book.pdf_file.url }}>
		            				<button type="button" class="btn btn-success btn-xs">
		            					<div class="col-sm-12 col-md-3"> <span class="glyphicon glyphicon-open"></span></div>
		            				</button>
		            			</a>
		            		</td>
		            		<td>{{ book.price }}</td>
		              {% endfor %}
		         {% endfor %}
         </table>
	            	
		</div>
	</div>
	</div>
	
{% endblock%}